services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - qdrant

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend

  postgres:
    image: postgres:16http://localhost:8000/docsFrontend:%20%20%20%20%20%20%20%20http://localhost:8501Qdrant:%20%20%20%20%20%20%20%20%20%20http://local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: edureg
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:v1.9.0
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  postgres_data:
  qdrant_data:
